"""Corrige conflito de backref

Revision ID: 0889cbc99bba
Revises: 
Create Date: 2025-07-10 20:15:53.687637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0889cbc99bba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    op.drop_table('lab')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lab',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('labTypeId', sa.INTEGER(), nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['labTypeId'], ['lab_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('labId', sa.INTEGER(), nullable=False),
    sa.Column('responsible', sa.VARCHAR(length=100), nullable=False),
    sa.Column('classGroupId', sa.INTEGER(), nullable=False),
    sa.Column('startTime', sa.DATETIME(), nullable=False),
    sa.Column('endTime', sa.DATETIME(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('repeatWeekly', sa.BOOLEAN(), nullable=True),
    sa.Column('repeatUntil', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['classGroupId'], ['class_group.id'], ),
    sa.ForeignKeyConstraint(['labId'], ['lab.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
